### PR TITLE
added configurable module for the left side of the chronograph visibl…

### PR DESCRIPTION
**Pull request by cybertim**
…e only in ambient mode

implemented my request: #1

### CODE REVIEW

**Comment by seahorsepip** [comment]
I'll test it later today and merge if no issues are found ^^

**Comment by seahorsepip** [comment]
It might be a good idea to make the startbutton, upper and lower dials complications so users can swap their positions and replace them if they don't find them necessary.

This could be done by bundling additional complications that simply supply identification data to notify the watchface service to draw a specific module.

**Comment by cybertim** [comment]
Yes, but the only place where these buttons are used are on the chronograph watch face.
I think putting effort in this would be nice, but not really necessary at the moment, since it will take a lot of work to introduce this.
 
Something which could be of more use would be an extra Module for Notifications and adding this module to all watch faces. This will free up one complication on all faces. And it probably less work but benefits everybody.

**Comment by seahorsepip** [comment]
Complications can be either declared as global, internal or even restricted for a specific watch face service so that's not an issue :)

And yes a notification module for every watch face seems to make sense though I'm still uncertain how to visually implement this.

Style:
1. Red dot like apple watch
2. Circle with count
3. Red dot with count

Position:
1. Top like apple watch
2. Bottom, indicating screen edge to swipe for notifications like apple watch.

Currently I'm leaning towards red dot with optional count at the bottom. So an additional settings screen with "OFF", "Unread notification dot", "Unread notification count", "All notification dot", "All notification count".

**Comment by cybertim** [comment]
I got my wear 2.0 a week ago. Last time I made something for native android has to be 5 years ago for android ICS. But with android studio nowadays I was able to modify the chrono face quick easily, luckily.

My thoughts on the notification counter: I would just create a white (or accent coloured) circle/dot with count. And based on the watchface, place the circle on a specific location when there is a notification.

On the round faces with 4 complications you can place it between de right and bottom comp., like the elegant analog default face. And on the chronograph I would place it in the centre of the 'seconds' circle. On the digital faces maybe in a corner?
A solid filled dot when awake, and a circle-outline in ambient to prevent burn-ins.

**Pull request merged**
